### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by dirkschumacher** [ericgj/elm-quantiles#1]
Interesting package. I was thinking about doing the same :)

It would be cool if you added a license. [BSD-3](https://github.com/rtfeldman/elm-css/blob/master/LICENSE) clause seems to be a popular license.

**Comment by ericgj** [comment]
Cool, yeah the elm-package default says BSD-3 but I could add a license file.  

The API is kind of experimental in a number of ways and I'd love to get any feedback on it, not sure I like it :)   Also - it really needs tests.

**Comment by ericgj** [comment]
added.

**Comment by dirkschumacher** [comment]
Great. I just figured out how to add [tests](https://github.com/dirkschumacher/elm-ecdf) ;)
